kind: pipeline
name: auth
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compose
    image: linuxserver/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: auth
        path: /drone/src/src/auth
    commands:
      - docker build -f ./src/auth/Iot.Auth.HttpApi.Host/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/iot-auth:dev .

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
---

kind: pipeline
name: admin
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compose
    image: linuxserver/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: iot-admin
        path: /drone/src/src/admin
    commands:
      - docker build -f ./src/admin/Iot.Admin.HttpApi.Host/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/iot-admin:dev .

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock



---

kind: pipeline
name: docker
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compose
    image: linuxserver/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: localtime
        path: /etc/localtime
    commands:
      - docker-compose down && docker-compose up -d
      - docker system prune -f
      - docker restart nginx

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: localtime
    host:
      path: /etc/localtime

depends_on:
  - admin
  - auth