version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./cert:/cert
      - /etc/localtime:/etc/localtime
    ports:
      - 80:80
      - 443:443
    networks:
      - token

    
  mssql:
      image: mcr.microsoft.com/mssql/server:2017-latest
      container_name: mssql
      restart: always
      volumes:
        - ./data/mssql:/var/opt/mssql/data
        - /etc/localtime:/etc/localtime
      environment:
        - "MSSQL_SA_PASSWORD=dd666666"
        - "ACCEPT_EULA=Y"
        - "TZ=Asia/Shanghai"
      ports:
        - 1433:1433
      networks:
        - token

  redis:
      image: redis
      container_name: redis
      restart: always
      networks:
        - token
      volumes:
        - /etc/localtime:/etc/localtime

networks:
  token:
    external: true
# 指向外部docker网络，第一次执行需要创建网络  docker network create token