// <auto-generated />
using System;
using Iot.EntityFrameworkCore.DbMigrator.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iot.EntityFrameworkCore.Dbmigrator.Migrations
{
    [DbContext(typeof(IotMigrationsDbContext))]
    [Migration("20220905155057_createDeviceType")]
    partial class createDeviceType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Functions.MenuRoleFunction", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("MenuId", "RoleId");

                    b.ToTable("menuRoleFunctions", (string)null);

                    b.HasComment("菜单角色配置");

                    b.HasData(
                        new
                        {
                            MenuId = new Guid("4b225133-a7b7-49c8-a74b-e042c44ce821"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("fdc46d94-45fb-4ab1-aa0f-0e9f6e6d8865"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("08e9e023-e5cb-4e94-8a42-e20fe8dc2785"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("95829cd3-acb8-4731-94a2-a8c67dabc7df"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("396627d4-5fd1-411c-8591-4466fd9703db"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("9b8045cd-c324-4aa6-9e50-f1d8f59cd55c"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("0a89e690-4d8c-439d-a22f-ee6c650a2533"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("67be2d62-6543-4ab6-a5e3-2ef986a87956"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        },
                        new
                        {
                            MenuId = new Guid("bf0e44dd-e0c5-4cfa-8b74-5c89a4537d0d"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        });
                });

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Functions.UserRoleFunction", b =>
                {
                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserInfoId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserInfoId", "RoleId");

                    b.ToTable("UserRoleFunctions", (string)null);

                    b.HasComment("用户角色配置");

                    b.HasData(
                        new
                        {
                            UserInfoId = new Guid("4754a271-42d5-4e0d-8298-41b19dd00ab3"),
                            RoleId = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8")
                        });
                });

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("标题");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus", (string)null);

                    b.HasComment("菜单权限控制");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b225133-a7b7-49c8-a74b-e042c44ce821"),
                            Component = "@/pages/home/index",
                            ConcurrencyStamp = "3df3a0ea54f540928933a948e9e3e235",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5367),
                            ExtraProperties = "{}",
                            Icon = "HomeOutlined",
                            Index = 0,
                            IsDeleted = false,
                            Name = "首页",
                            Path = "/admin",
                            Title = "首页"
                        },
                        new
                        {
                            Id = new Guid("fdc46d94-45fb-4ab1-aa0f-0e9f6e6d8865"),
                            Component = "",
                            ConcurrencyStamp = "99871401c4d34096b2b88b77ef62509e",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5376),
                            ExtraProperties = "{}",
                            Icon = "SettingOutlined",
                            Index = 1,
                            IsDeleted = false,
                            Name = "权限管理",
                            Path = "/authority",
                            Title = "权限管理"
                        },
                        new
                        {
                            Id = new Guid("08e9e023-e5cb-4e94-8a42-e20fe8dc2785"),
                            Component = "@/pages/authority/roles/index",
                            ConcurrencyStamp = "e5c6d8fd3ce34d68a94b11a73632d88c",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5387),
                            ExtraProperties = "{}",
                            Index = 0,
                            IsDeleted = false,
                            Name = "角色管理",
                            ParentId = new Guid("fdc46d94-45fb-4ab1-aa0f-0e9f6e6d8865"),
                            Path = "/authority/role",
                            Title = "角色管理"
                        },
                        new
                        {
                            Id = new Guid("95829cd3-acb8-4731-94a2-a8c67dabc7df"),
                            Component = "@/pages/authority/users/index",
                            ConcurrencyStamp = "4eee053e7823444d8ff742bc3c041516",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5392),
                            ExtraProperties = "{}",
                            Index = 1,
                            IsDeleted = false,
                            Name = "用户管理",
                            ParentId = new Guid("fdc46d94-45fb-4ab1-aa0f-0e9f6e6d8865"),
                            Path = "/authority/user",
                            Title = "用户管理"
                        },
                        new
                        {
                            Id = new Guid("396627d4-5fd1-411c-8591-4466fd9703db"),
                            Component = "@/pages/authority/menus/index",
                            ConcurrencyStamp = "e8a66eb8e2a546969342cb447b08ea90",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5402),
                            ExtraProperties = "{}",
                            Index = 2,
                            IsDeleted = false,
                            Name = "菜单管理",
                            ParentId = new Guid("fdc46d94-45fb-4ab1-aa0f-0e9f6e6d8865"),
                            Path = "/authority/menu",
                            Title = "菜单管理"
                        },
                        new
                        {
                            Id = new Guid("9b8045cd-c324-4aa6-9e50-f1d8f59cd55c"),
                            ConcurrencyStamp = "f34b921c9fc740ab8eceee7dffa6a089",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5407),
                            ExtraProperties = "{}",
                            Icon = "DashboardOutlined",
                            Index = 2,
                            IsDeleted = false,
                            Name = "设备",
                            Path = "/devices",
                            Title = "设备"
                        },
                        new
                        {
                            Id = new Guid("0a89e690-4d8c-439d-a22f-ee6c650a2533"),
                            Component = "@/pages/devices/template/index",
                            ConcurrencyStamp = "cac51811ffd14d50887ca532ddbef5b1",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5413),
                            ExtraProperties = "{}",
                            Index = 0,
                            IsDeleted = false,
                            Name = "设备模板",
                            ParentId = new Guid("9b8045cd-c324-4aa6-9e50-f1d8f59cd55c"),
                            Path = "/devices/template",
                            Title = "设备模板"
                        },
                        new
                        {
                            Id = new Guid("bf0e44dd-e0c5-4cfa-8b74-5c89a4537d0d"),
                            Component = "@/pages/devices/admin/index",
                            ConcurrencyStamp = "c833d87b3179478fa2daf5c6c5982664",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5421),
                            ExtraProperties = "{}",
                            Index = 2,
                            IsDeleted = false,
                            Name = "设备管理",
                            ParentId = new Guid("9b8045cd-c324-4aa6-9e50-f1d8f59cd55c"),
                            Path = "/devices/admin",
                            Title = "设备管理"
                        },
                        new
                        {
                            Id = new Guid("67be2d62-6543-4ab6-a5e3-2ef986a87956"),
                            Component = "@/pages/devices/running-log/index",
                            ConcurrencyStamp = "207886490bd945538b6458135610a83e",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5417),
                            ExtraProperties = "{}",
                            Index = 1,
                            IsDeleted = false,
                            Name = "设备运行日志",
                            ParentId = new Guid("9b8045cd-c324-4aa6-9e50-f1d8f59cd55c"),
                            Path = "/devices/running-log",
                            Title = "设备运行日志"
                        });
                });

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("编码");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("上一级id");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasComment("角色");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6061aafc-2312-4618-a579-5e8f6000c9b8"),
                            Code = "admin",
                            ConcurrencyStamp = "5d998894cb5b4465858a81a0687b17b8",
                            CreationTime = new DateTime(2022, 9, 5, 23, 50, 56, 767, DateTimeKind.Local).AddTicks(5275),
                            ExtraProperties = "{}",
                            Index = 0,
                            IsDeleted = false,
                            Name = "管理员",
                            Remark = "系统管理员"
                        });
                });

            modelBuilder.Entity("Iot.Device.Devices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<Guid?>("DeviceTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stats")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTemplateId");

                    b.HasIndex("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("IotDevices", (string)null);

                    b.HasComment("设备信息");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b7b9606-c979-4022-8506-ae2ef718298c"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceTemplateId = new Guid("0e2b485e-beb8-458c-8c38-67fbac758f0d"),
                            IsDeleted = false,
                            Remark = "",
                            Stats = 1,
                            UserInfoId = new Guid("4754a271-42d5-4e0d-8298-41b19dd00ab3")
                        });
                });

            modelBuilder.Entity("Iot.Devices.DeviceRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Id");

                    b.ToTable("DeviceRunLogs", (string)null);

                    b.HasComment("设备运行信息");
                });

            modelBuilder.Entity("Iot.Devices.DeviceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("图标");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("模板名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("类型");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("用户id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTemplates", (string)null);

                    b.HasComment("设备模板");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e2b485e-beb8-458c-8c38-67fbac758f0d"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "https://tokeniot.oss-cn-shenzhen.aliyuncs.com/icon/Dht.png",
                            IsDeleted = false,
                            Name = "温度计",
                            Remark = "备注",
                            Type = "温度计",
                            UserId = new Guid("4754a271-42d5-4e0d-8298-41b19dd00ab3")
                        });
                });

            modelBuilder.Entity("Iot.Users.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("账号");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("头像");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Introduce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("昵称");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("密码");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("手机号");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasComment("账号状态");

                    b.Property<string>("WeChatOpenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("WeChatOpenId");

                    b.HasIndex("AccountNumber", "Password");

                    b.ToTable("IotUserInfo", (string)null);

                    b.HasComment("用户信息");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4754a271-42d5-4e0d-8298-41b19dd00ab3"),
                            AccountNumber = "admin",
                            Avatar = "https://xiaohuchat.oss-cn-beijing.aliyuncs.com/ima/admin.jpg",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Introduce = "超级管理员",
                            IsDeleted = false,
                            Name = "管理员",
                            Password = "dd666666",
                            PhoneNumber = "13049809673",
                            State = 0
                        });
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("ApplicationName");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("BrowserInfo");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ClientId");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ClientIpAddress");

                    b.Property<string>("ClientName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ClientName");

                    b.Property<string>("Comments")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Comments");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("CorrelationId");

                    b.Property<string>("Exceptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int")
                        .HasColumnName("ExecutionDuration");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("HttpMethod");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("HttpStatusCode");

                    b.Property<Guid?>("ImpersonatorTenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImpersonatorTenantId");

                    b.Property<string>("ImpersonatorTenantName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ImpersonatorTenantName");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImpersonatorUserId");

                    b.Property<string>("ImpersonatorUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ImpersonatorUserName");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<string>("TenantName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("TenantName");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Url");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExecutionTime");

                    b.HasIndex("TenantId", "UserId", "ExecutionTime");

                    b.ToTable("AbpAuditLogs", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.AuditLogAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditLogId");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int")
                        .HasColumnName("ExecutionDuration");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExecutionTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("MethodName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("MethodName");

                    b.Property<string>("Parameters")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Parameters");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ServiceName");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.HasIndex("TenantId", "ServiceName", "MethodName", "ExecutionTime");

                    b.ToTable("AbpAuditLogActions", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.EntityChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuditLogId");

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ChangeTime");

                    b.Property<byte>("ChangeType")
                        .HasColumnType("tinyint")
                        .HasColumnName("ChangeType");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("EntityId");

                    b.Property<Guid?>("EntityTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityTypeFullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("EntityTypeFullName");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.HasIndex("TenantId", "EntityTypeFullName", "EntityId");

                    b.ToTable("AbpEntityChanges", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.EntityPropertyChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("NewValue");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("OriginalValue");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("PropertyName");

                    b.Property<string>("PropertyTypeFullName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PropertyTypeFullName");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("EntityChangeId");

                    b.ToTable("AbpEntityPropertyChanges", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.FeatureManagement.FeatureValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProviderName", "ProviderKey")
                        .IsUnique()
                        .HasFilter("[ProviderName] IS NOT NULL AND [ProviderKey] IS NOT NULL");

                    b.ToTable("AbpFeatureValues", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.SettingManagement.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProviderName", "ProviderKey")
                        .IsUnique()
                        .HasFilter("[ProviderName] IS NOT NULL AND [ProviderKey] IS NOT NULL");

                    b.ToTable("AbpSettings", (string)null);
                });

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Functions.MenuRoleFunction", b =>
                {
                    b.HasOne("Iot.Auth.Domain.Roles.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iot.Auth.Domain.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Iot.Auth.Domain.Roles.Functions.UserRoleFunction", b =>
                {
                    b.HasOne("Iot.Auth.Domain.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iot.Users.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Iot.Device.Devices", b =>
                {
                    b.HasOne("Iot.Devices.DeviceTemplate", "DeviceTemplate")
                        .WithMany()
                        .HasForeignKey("DeviceTemplateId");

                    b.HasOne("Iot.Users.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId");

                    b.Navigation("DeviceTemplate");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Iot.Devices.DeviceTemplate", b =>
                {
                    b.HasOne("Iot.Users.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.AuditLogAction", b =>
                {
                    b.HasOne("Volo.Abp.AuditLogging.AuditLog", null)
                        .WithMany("Actions")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.EntityChange", b =>
                {
                    b.HasOne("Volo.Abp.AuditLogging.AuditLog", null)
                        .WithMany("EntityChanges")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.EntityPropertyChange", b =>
                {
                    b.HasOne("Volo.Abp.AuditLogging.EntityChange", null)
                        .WithMany("PropertyChanges")
                        .HasForeignKey("EntityChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.AuditLog", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("EntityChanges");
                });

            modelBuilder.Entity("Volo.Abp.AuditLogging.EntityChange", b =>
                {
                    b.Navigation("PropertyChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
